### PR TITLE
Update README.md and add photos

### PR DESCRIPTION
**Pull request by Barzan-Dawood**
### Have you read the [Contributing Guidelines](https://github.com/SamarpanCoder2002/Generation/blob/main/CONTRIBUTING.md) ?

(yes)

### Description

(The project is very cool, I really like it)

### Checklist

- [yes] I've read the contribution guidelines.
- [yes] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

(yes)

## Issue number

(2.0)

Then add a blue tick to know whether the user read the message or not
And
Add a like button to the sent image

### CODE REVIEW

**Comment by Barzan-Dawood** [comment]
Please reply as soon as possible Do you then approve or reject the application ?

**Review by SamarpanCoder2002 — CHANGES_REQUESTED** [review]
Nice picture edited or taken a nice screenshot. But the double right sign is not satisfactory. Please try to improve it.

👉 Points need to change:

- Use this [tick image](https://img.icons8.com/ios-filled/512/double-tick.png) with your color, you attached. (readme_documents pic 9.png)

-  In readme_documents pic 10.png, use this kind of [heart icon](readme_documents) in both fill and not fill form. Your used heart in somewhat sharp that not perfect for the compare to the rest of the design.

- Change heart border and fill color green(Use same color used in profile_pic border:  Refer to readme_documents image 10.png)

- Make sure under readme_documents folder, 9.png and 10.png having transparent background like other images. Currently, the two images have a white background.

@Barzan-Dawood

**Comment by Barzan-Dawood** [comment]
Hello, I have updated the required request!

**Comment by Barzan-Dawood** [comment]
Hi teacher .  Have you looked at changes in the pull request?  Please, if there are any errors in the post, please reply to me

**Review by SamarpanCoder2002 — APPROVED** [review]

**Comment by SamarpanCoder2002** [comment]
> Hi teacher . Have you looked at changes in the pull request? Please, if there are any errors in the post, please reply to me

The picture looks nice... Thanks for making the pull request.

**Comment by Barzan-Dawood** [comment]
Please help. You agree to the withdrawal request, and I will not understand
it, because this is the first time I am making a withdrawal request

‫في الأربعاء، 25 يناير 2023 في 9:55 ص تمت كتابة ما يلي بواسطة ‪Samarpan
Dasgupta‬‏ ***@***.***‬‏>:‬

**Pull request merged**
